### ISSUE TITLE
Arduino code for Lights

### ISSUE THREAD

**Issue by ksakash** [AUV-IITK/Hyperion-Software#13]
Since we now have an underwater light also, so we need to include its code also in our present arduino code to run it.

**Comment by Suryansh470** [comment]
we need to just get the pin numbers from the electrical subsystem and then declare them in ```void setup()``` and use ```digitalWrite(pinNumber,High/Low) or analogWrite(pinNumber, pwm)``` to turn the light on depending upon the intensity.

**Comment by Suryansh470** [comment]
@naishadhparmar @ksakash what is the status on this issue ???? This is a fairly straight forward issue so it need not take much time ...... if its completed, then close it

**Comment by Suryansh470** [comment]
I think we should close this issue since it has been resolved from the software side ...
